
package dtv.xcenter.poslog.ws.v21;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PoslogObjReceiverApi", targetNamespace = "http://v21.ws.poslog.xcenter.dtv/")
@XmlSeeAlso({
    dtv.xcenter.poslog.ws.v21.ObjectFactory.class,
    dtv.xcenter.poslog_ext.ws.v21.ObjectFactory.class
})
public interface PoslogObjReceiverApi {


    /**
     * 
     * @param transaction
     * @throws PoslogObjReceiverException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "postTransaction", targetNamespace = "http://v21.ws.poslog.xcenter.dtv/", className = "dtv.xcenter.poslog.ws.v21.PostTransaction")
    @ResponseWrapper(localName = "postTransactionResponse", targetNamespace = "http://v21.ws.poslog.xcenter.dtv/", className = "dtv.xcenter.poslog.ws.v21.PostTransactionResponse")
    @Action(input = "http://v21.ws.poslog.xcenter.dtv/PoslogObjReceiverApi/postTransactionRequest", output = "http://v21.ws.poslog.xcenter.dtv/PoslogObjReceiverApi/postTransactionResponse", fault = {
        @FaultAction(className = PoslogObjReceiverException_Exception.class, value = "http://v21.ws.poslog.xcenter.dtv/PoslogObjReceiverApi/postTransaction/Fault/PoslogObjReceiverException")
    })
    public void postTransaction(
        @WebParam(name = "transaction", targetNamespace = "")
        TransactionType transaction)
        throws PoslogObjReceiverException_Exception
    ;

}
