
package dtv.xcenter.poslog.ws.v21;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PoslogObjReceiverApiService", targetNamespace = "http://v21.ws.poslog.xcenter.dtv/", wsdlLocation = "file:/C:/Temp/PoslogObjReceiverApiService.wsdl")
public class PoslogObjReceiverApiService
    extends Service
{

    private final static URL POSLOGOBJRECEIVERAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException POSLOGOBJRECEIVERAPISERVICE_EXCEPTION;
    private final static QName POSLOGOBJRECEIVERAPISERVICE_QNAME = new QName("http://v21.ws.poslog.xcenter.dtv/", "PoslogObjReceiverApiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Temp/PoslogObjReceiverApiService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSLOGOBJRECEIVERAPISERVICE_WSDL_LOCATION = url;
        POSLOGOBJRECEIVERAPISERVICE_EXCEPTION = e;
    }

    public PoslogObjReceiverApiService() {
        super(__getWsdlLocation(), POSLOGOBJRECEIVERAPISERVICE_QNAME);
    }

    public PoslogObjReceiverApiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSLOGOBJRECEIVERAPISERVICE_QNAME, features);
    }

    public PoslogObjReceiverApiService(URL wsdlLocation) {
        super(wsdlLocation, POSLOGOBJRECEIVERAPISERVICE_QNAME);
    }

    public PoslogObjReceiverApiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSLOGOBJRECEIVERAPISERVICE_QNAME, features);
    }

    public PoslogObjReceiverApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PoslogObjReceiverApiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PoslogObjReceiverApi
     */
    @WebEndpoint(name = "PoslogObjReceiverApiPort")
    public PoslogObjReceiverApi getPoslogObjReceiverApiPort() {
        return super.getPort(new QName("http://v21.ws.poslog.xcenter.dtv/", "PoslogObjReceiverApiPort"), PoslogObjReceiverApi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PoslogObjReceiverApi
     */
    @WebEndpoint(name = "PoslogObjReceiverApiPort")
    public PoslogObjReceiverApi getPoslogObjReceiverApiPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://v21.ws.poslog.xcenter.dtv/", "PoslogObjReceiverApiPort"), PoslogObjReceiverApi.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSLOGOBJRECEIVERAPISERVICE_EXCEPTION!= null) {
            throw POSLOGOBJRECEIVERAPISERVICE_EXCEPTION;
        }
        return POSLOGOBJRECEIVERAPISERVICE_WSDL_LOCATION;
    }

}
