
package dtv.xcenter.poslog.ws.v21;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PoslogObjReceiverException", targetNamespace = "http://v21.ws.poslog.xcenter.dtv/")
public class PoslogObjReceiverException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PoslogObjReceiverException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PoslogObjReceiverException_Exception(String message, PoslogObjReceiverException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PoslogObjReceiverException_Exception(String message, PoslogObjReceiverException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: dtv.xcenter.poslog.ws.v21.PoslogObjReceiverException
     */
    public PoslogObjReceiverException getFaultInfo() {
        return faultInfo;
    }

}
